target 'Photoshare' do
  use_frameworks!

pod 'JSQMessagesViewController', '7.3.3'
pod 'IDMPhotoBrowser'

pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'

pod 'ImagePicker'

pod 'ProgressHUD'
pod 'MBProgressHUD'

end
